# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_DB: affiliate_dev
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
